function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function preserveCase(source, target) {
  if (!source) {
    return target;
  }

  if (source === source.toUpperCase()) {
    return target.toUpperCase();
  }

  if (source[0] === source[0].toUpperCase()) {
    return `${target[0].toUpperCase()}${target.slice(1)}`;
  }

  return target;
}

const phraseReplacements = [
  ["n/a", "n/d"],
  ["seed dirt global", "graine globale de terre"],
  ["seed water global", "graine globale d'eau"],
  ["aspect ratio du front", "rapport d'aspect du front"],
  ["shapeseed du front", "graine de forme du front"],
  ["densityseed du front", "graine de densité du front"],
  ["champ spatial dirt", "champ spatial de terre"],
  ["champ spatial water", "champ spatial d'eau"],
  ["masque de flip", "masque de retournement"],
  ["flip des", "retournement des"],
  ["spawn des royaumes", "apparition des royaumes"],
  ["spawn du royaume blanc", "apparition du royaume blanc"],
  ["spawn du royaume noir", "apparition du royaume noir"],
  ["white water denied cells", "cellules refusées par l'eau du royaume blanc"],
  ["black water denied cells", "cellules refusées par l'eau du royaume noir"],
  ["water denied cells", "cellules refusées par l'eau"],
  ["white hidden enemy pieces", "pièces ennemies masquées côté blanc"],
  ["black hidden enemy pieces", "pièces ennemies masquées côté noir"],
  ["hidden enemy pieces", "pièces ennemies masquées"],
  ["concealing fog cells", "cellules de brouillard occultantes"],
  ["fog cells", "cellules de brouillard"],
  ["hidden pieces", "pièces masquées"],
  ["white blood debt", "dette de sang blanche"],
  ["black blood debt", "dette de sang noire"],
  ["blood debt", "dette de sang"],
  ["a chaque", "à chaque"],
  ["a partir", "à partir"],
  ["a la", "à la"],
  ["a l'", "à l'"],
  ["a droite", "à droite"],
  ["a gauche", "à gauche"],
  ["a deux", "à deux"],
  ["a grand", "à grand"],
  ["a grande", "à grande"],
  ["mise a jour", "mise à jour"],
  ["bascule a", "bascule à"],
  ["plus a", "plus à"],
  ["grace a", "grâce à"],
  ["piecewise linear", "linéaire par morceaux"],
  ["support observe des spawns blanc et noir", "support observé des zones d'apparition blanche et noire"],
  ["repartition des colonnes de spawn des royaumes blanc et noir", "répartition des colonnes d'apparition des royaumes blanc et noir"],
  ["le basculement early/late des coffres est lisible", "le basculement début/fin des coffres est lisible"],
  ["or early observe", "or observé en début de partie"],
  ["or late observe", "or observé en fin de partie"],
  ["early observe", "début observé"],
  ["early attendu", "début attendu"],
  ["late observe", "fin observée"],
  ["late attendu", "fin attendue"],
  ["stochastic", "stochastique"],
  ["gate d'arrivee", "déclenchement d'arrivée"]
];

const wordReplacements = new Map([
  ["academique", "académique"],
  ["academiques", "académiques"],
  ["agregee", "agrégée"],
  ["agregees", "agrégées"],
  ["aleatoire", "aléatoire"],
  ["aleatoires", "aléatoires"],
  ["amelioration", "amélioration"],
  ["ameliorations", "améliorations"],
  ["apres", "après"],
  ["arrivee", "arrivée"],
  ["arrivees", "arrivées"],
  ["asymetrique", "asymétrique"],
  ["asymetriques", "asymétriques"],
  ["batiment", "bâtiment"],
  ["batiments", "bâtiments"],
  ["bibliotheque", "bibliothèque"],
  ["boite", "boîte"],
  ["categorielle", "catégorielle"],
  ["categorielles", "catégorielles"],
  ["coherence", "cohérence"],
  ["coherente", "cohérente"],
  ["coherentes", "cohérentes"],
  ["completee", "complétée"],
  ["completes", "complétés"],
  ["completement", "complètement"],
  ["correle", "corrélé"],
  ["correlee", "corrélée"],
  ["correlees", "corrélées"],
  ["correlation", "corrélation"],
  ["correlations", "corrélations"],
  ["correles", "corrélés"],
  ["cote", "côté"],
  ["cotes", "côtés"],
  ["defaut", "défaut"],
  ["deformation", "déformation"],
  ["deformations", "déformations"],
  ["degre", "degré"],
  ["degres", "degrés"],
  ["deja", "déjà"],
  ["decrite", "décrite"],
  ["decrites", "décrites"],
  ["decrits", "décrits"],
  ["depend", "dépend"],
  ["dependance", "dépendance"],
  ["dependances", "dépendances"],
  ["dependante", "dépendante"],
  ["dependantes", "dépendantes"],
  ["dependent", "dépendent"],
  ["depart", "départ"],
  ["design", "conception"],
  ["derivee", "dérivée"],
  ["derivees", "dérivées"],
  ["derives", "dérivés"],
  ["deriver", "dériver"],
  ["discrete", "discrète"],
  ["discretes", "discrètes"],
  ["discretisee", "discrétisée"],
  ["discretisees", "discrétisées"],
  ["ecart", "écart"],
  ["echantillonnage", "échantillonnage"],
  ["echantillonne", "échantillonne"],
  ["echelle", "échelle"],
  ["ecrit", "écrit"],
  ["ecrite", "écrite"],
  ["ecrites", "écrites"],
  ["egalement", "également"],
  ["egaux", "égaux"],
  ["eloignee", "éloignée"],
  ["eloignees", "éloignées"],
  ["emergence", "émergence"],
  ["entree", "entrée"],
  ["entrees", "entrées"],
  ["equilibre", "équilibre"],
  ["equilibree", "équilibrée"],
  ["equilibrees", "équilibrées"],
  ["equivalente", "équivalente"],
  ["equivalentes", "équivalentes"],
  ["equiprobable", "équiprobable"],
  ["equiprobables", "équiprobables"],
  ["etat", "état"],
  ["etats", "états"],
  ["evenement", "événement"],
  ["evenements", "événements"],
  ["evaluation", "évaluation"],
  ["evaluee", "évaluée"],
  ["evaluees", "évaluées"],
  ["exposee", "exposée"],
  ["exposees", "exposées"],
  ["fenetre", "fenêtre"],
  ["fenetres", "fenêtres"],
  ["geometrie", "géométrie"],
  ["geometrique", "géométrique"],
  ["geometriques", "géométriques"],
  ["geometriquement", "géométriquement"],
  ["genere", "génère"],
  ["generee", "générée"],
  ["generees", "générées"],
  ["generes", "générés"],
  ["generation", "génération"],
  ["generations", "générations"],
  ["idee", "idée"],
  ["idees", "idées"],
  ["immediatement", "immédiatement"],
  ["integre", "intégré"],
  ["integree", "intégrée"],
  ["integrees", "intégrées"],
  ["inventories", "inventoriés"],
  ["interet", "intérêt"],
  ["interets", "intérêts"],
  ["intermediaire", "intermédiaire"],
  ["intermediaires", "intermédiaires"],
  ["irregularite", "irrégularité"],
  ["irregularites", "irrégularités"],
  ["legerement", "légèrement"],
  ["mathematique", "mathématique"],
  ["mathematiques", "mathématiques"],
  ["mecanique", "mécanique"],
  ["meme", "même"],
  ["methode", "méthode"],
  ["methodes", "méthodes"],
  ["meteo", "météo"],
  ["modele", "modèle"],
  ["modeles", "modèles"],
  ["modelisante", "modélisante"],
  ["modelisantes", "modélisantes"],
  ["numerique", "numérique"],
  ["numeriques", "numériques"],
  ["opacite", "opacité"],
  ["opacites", "opacités"],
  ["parametre", "paramètre"],
  ["parametres", "paramètres"],
  ["personnalisee", "personnalisée"],
  ["personnalisees", "personnalisées"],
  ["phenomene", "phénomène"],
  ["phenomenes", "phénomènes"],
  ["plutot", "plutôt"],
  ["ponderee", "pondérée"],
  ["ponderees", "pondérées"],
  ["prealable", "préalable"],
  ["preserve", "préserve"],
  ["preservee", "préservée"],
  ["preservees", "préservées"],
  ["preserver", "préserver"],
  ["presente", "présente"],
  ["presentes", "présentes"],
  ["priorite", "priorité"],
  ["privilegie", "privilégie"],
  ["privilegiee", "privilégiée"],
  ["privilegiees", "privilégiées"],
  ["privilegier", "privilégier"],
  ["prives", "privés"],
  ["probabilite", "probabilité"],
  ["probabilites", "probabilités"],
  ["procedurale", "procédurale"],
  ["procedurales", "procédurales"],
  ["proceduraux", "procéduraux"],
  ["proprietes", "propriétés"],
  ["qualite", "qualité"],
  ["quantifiee", "quantifiée"],
  ["quantifiees", "quantifiées"],
  ["recompense", "récompense"],
  ["recompenses", "récompenses"],
  ["reclasses", "reclassés"],
  ["recurrente", "récurrente"],
  ["recurrentes", "récurrentes"],
  ["reference", "référence"],
  ["references", "références"],
  ["repartition", "répartition"],
  ["resumables", "résumables"],
  ["schema", "schéma"],
  ["schemas", "schémas"],
  ["selection", "sélection"],
  ["selectionne", "sélectionne"],
  ["selectionnee", "sélectionnée"],
  ["selectionnees", "sélectionnées"],
  ["selectionner", "sélectionner"],
  ["serialise", "sérialisé"],
  ["serialisee", "sérialisée"],
  ["serialises", "sérialisés"],
  ["serialisees", "sérialisées"],
  ["specifique", "spécifique"],
  ["specifiques", "spécifiques"],
  ["simetrie", "symétrie"],
  ["sous-systeme", "sous-système"],
  ["sous-systemes", "sous-systèmes"],
  ["systeme", "système"],
  ["systemes", "systèmes"],
  ["symetrique", "symétrique"],
  ["symetriques", "symétriques"],
  ["deterministe", "déterministe"],
  ["deterministes", "déterministes"],
  ["strategique", "stratégique"],
  ["strategiques", "stratégiques"],
  ["supplementaire", "supplémentaire"],
  ["supplementaires", "supplémentaires"],
  ["tache", "tâche"],
  ["taches", "tâches"],
  ["coeur", "cœur"],
  ["definie", "définie"],
  ["definies", "définies"],
  ["ecrire", "écrire"],
  ["esperance", "espérance"],
  ["legitime", "légitime"],
  ["metrique", "métrique"],
  ["mobilisee", "mobilisée"],
  ["recurrent", "récurrent"],
  ["theorique", "théorique"],
  ["theoriques", "théoriques"],
  ["tiree", "tirée"],
  ["tirees", "tirées"],
  ["transformee", "transformée"],
  ["transformees", "transformées"],
  ["tronquee", "tronquée"],
  ["tronquees", "tronquées"],
  ["utilisee", "utilisée"],
  ["utilisees", "utilisées"],
  ["variete", "variété"],
  ["visibilite", "visibilité"],
  ["observee", "observée"],
  ["observees", "observées"],
  ["observe", "observé"],
  ["observes", "observés"],
  ["duree", "durée"],
  ["durees", "durées"],
  ["reel", "réel"],
  ["reelle", "réelle"],
  ["reelles", "réelles"],
  ["ciblee", "ciblée"],
  ["ciblees", "ciblées"],
  ["parametree", "paramétrée"],
  ["parametrees", "paramétrées"],
  ["scenario", "scénario"],
  ["scenarios", "scénarios"],
  ["bin", "classe"],
  ["bins", "classes"],
  ["spawn", "apparition"],
  ["spawns", "apparitions"],
  ["flip", "retournement"],
  ["turn", "tour"]
]);

export function reportText(value) {
  if (typeof value !== "string" || value.length === 0) {
    return value;
  }

  let output = value;

  for (const [from, to] of phraseReplacements) {
    output = output.replace(new RegExp(escapeRegExp(from), "gi"), (match) => preserveCase(match, to));
  }

  for (const [from, to] of wordReplacements.entries()) {
    output = output.replace(new RegExp(`\\b${escapeRegExp(from)}\\b`, "giu"), (match) => preserveCase(match, to));
  }

  return output;
}